"""cambio en la estructura de la base de datos

Revision ID: e9f2c4f41979
Revises: 3c87c93c5851
Create Date: 2026-04-20 20:11:10.461818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f2c4f41979'
down_revision: Union[str, Sequence[str], None] = '3c87c93c5851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'categories', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_table('companies')
    # ### end Alembic commands ###
